Adapting Dockerfile for k8s-compatible deployment

diff --git a/docker/kubernetes/spark/Dockerfile b/docker/kubernetes/spark/Dockerfile
--- a/docker/kubernetes/spark/Dockerfile
+++ b/docker/kubernetes/spark/Dockerfile
@@ -15,9 +15,41 @@
 # limitations under the License.
 #
 
-ARG base_img
+FROM openjdk:8-alpine
 
-FROM $base_img
+ARG spark_uid=185
+
+# Before building the docker image, first build and make a Spark distribution following
+# the instructions in http://spark.apache.org/docs/latest/building-spark.html.
+# If this docker file is being used in the context of building your images from a Spark
+# distribution, the docker build command should be invoked from the top level directory
+# of the Spark distribution. E.g.:
+# docker build -t spark:latest -f kubernetes/dockerfiles/spark/Dockerfile .
+
+RUN set -ex && \
+    apk upgrade --no-cache && \
+    ln -s /lib /lib64 && \
+    apk add --no-cache bash tini libc6-compat linux-pam krb5 krb5-libs nss && \
+    mkdir -p /opt/spark && \
+    mkdir -p /opt/spark/examples && \
+    mkdir -p /opt/spark/work-dir && \
+    touch /opt/spark/RELEASE && \
+    rm /bin/sh && \
+    ln -sv /bin/bash /bin/sh && \
+    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
+    chgrp root /etc/passwd && chmod ug+rw /etc/passwd
+
+COPY jars /opt/spark/jars
+COPY bin /opt/spark/bin
+COPY sbin /opt/spark/sbin
+COPY kubernetes/dockerfiles/spark/entrypoint.sh /opt/
+COPY examples /opt/spark/examples
+COPY kubernetes/tests /opt/spark/tests
+COPY data /opt/spark/data
+
+ENV SPARK_HOME /opt/spark
+
+# Setting up COFFEA
 WORKDIR /
 
 # Reset to root to run installation tasks
@@ -115,8 +147,9 @@ ENV PYSPARK_MAJOR_PYTHON_VERSION="3"
 ENV PYTHONPATH=/opt/spark/python/lib/pyspark.zip:$PYTHONPATH
 
 WORKDIR /opt/spark/work-dir
+RUN chmod g+w /opt/spark/work-dir
+
 ENTRYPOINT [ "/opt/entrypoint.sh" ]
 
 # Specify the User that the actual main process will run as
-ARG spark_uid=185
 USER ${spark_uid}
